; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; recommended to pin to a version, see https://github.com/platformio/platform-espressif32/releases

[env]
platform = espressif32@ ^6.13.0
;https://github.com/platformio/platform-espressif32.git
;
framework = arduino
; For headless build add to the needed environment:
;   -DPROJECT_NO_SCREEN=1
; For onboard LED support add:
;   -DPROJECT_USE_BOARD_LED=1
; For LED polarity override add:
;   -DPROJECT_BOARD_LED_ACTIVE_LOW=1  ; LED is ON at LOW
;   -DPROJECT_BOARD_LED_ACTIVE_LOW=0  ; LED is ON at HIGH
; For LED brightness via PWM add:
;   -DPROJECT_BOARD_LED_BRIGHTNESS=32 ; range 0..255
; OTA override examples:
;   -DPROJECT_OTA_HOSTNAME=\"my-esp32-bridge\"
;   -DPROJECT_OTA_PASSWORD=\"change-me\"
build_flags =
	-std=gnu++17
	-DPROJECT_NETWORK_TX_CHUNK_SIZE=1460
monitor_speed = 460800

build_type = debug
debug_build_flags = -Ofast

monitor_filters = esp32_exception_decoder

;upload_port = COM26
monitor_port = COM26

;-O0 -g3 -ggdb
lib_deps =
	gyverlibs/GTL@^1.3.5
	gyverlibs/Settings@^1.3.13
	gyverlibs/StringUtils@^1.5.3
	gyverlibs/mString@^1.7.3
	gyverlibs/GTimer@^1.1.1
	adafruit/Adafruit SSD1306@^2.5.15

build_unflags = -std=gnu++11

[env:esp32-c3-devkitm-1]
board = esp32-c3-devkitm-1
debug_tool = esp-builtin
debug_speed = 5000
board_build.partitions = default.csv
build_flags =
	${env.build_flags}
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DPROJECT_NETWORK_TX_QUEUE_LENGTH=64
	-DHW_VARIANT_ESP32_C3=1
	-DPROJECT_OTA_HOSTNAME=\"esp32-c3-uart\"

[env:esp32-c3-devkitm-1_ota]
board = esp32-c3-devkitm-1
debug_tool = esp-builtin
debug_speed = 5000
board_build.partitions = default.csv
upload_protocol = espota
upload_port = esp32-c3-uart.local
upload_flags =
	--port=3232
build_flags =
	${env.build_flags}
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DPROJECT_NETWORK_TX_QUEUE_LENGTH=64
	-DHW_VARIANT_ESP32_C3=1
	-DPROJECT_OTA_HOSTNAME=\"esp32-c3-uart\"

[env:lolin_s2_mini]
board = lolin_s2_mini
board_build.partitions = default.csv
board_build.arduino.memory_type = dio_qspi
build_flags =
	${env.build_flags}
	-DBOARD_HAS_PSRAM
	-DPROJECT_NETWORK_TX_QUEUE_LENGTH=256
	-DHW_VARIANT_ESP32_S2_MINI=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DPROJECT_USE_BOARD_LED=1
	-DPROJECT_BOARD_LED_BRIGHTNESS=128 ; range 0..255
	-DPROJECT_BOARD_LED_ACTIVE_LOW=0  ; LED is ON at HIGH
	-DPROJECT_OTA_HOSTNAME=\"esp32-s2-uart\"

[env:lolin_s2_mini_ota]
board = lolin_s2_mini
board_build.partitions = default.csv
board_build.arduino.memory_type = dio_qspi
upload_protocol = espota
upload_port = 192.168.0.222
upload_flags =
	--port=3232
build_flags =
	${env.build_flags}
	-DBOARD_HAS_PSRAM
	-DPROJECT_NETWORK_TX_QUEUE_LENGTH=256
	-DHW_VARIANT_ESP32_S2_MINI=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DPROJECT_USE_BOARD_LED=1
	-DPROJECT_BOARD_LED_BRIGHTNESS=128 ; range 0..255
	-DPROJECT_BOARD_LED_ACTIVE_LOW=0  ; LED is ON at HIGH
	-DPROJECT_OTA_HOSTNAME=\"esp32-s2-uart\"
